### ISSUE TITLE
[Feature request] Hide unused parameters as constants

### ISSUE THREAD

**Issue by JinraeKim** [cvxgrp/cvxpylayers#123]
I'd like to change the value of "Parameter" `x` for efficient multiple solves, which is not in the scope of cvxpylayer.
Instead, `A` is the Parameter for cvxpylayer.
MWE (minimum working example) is as follows.
```python3
import numpy as np
import cvxpy as cp
import torch
from cvxpylayers.torch import CvxpyLayer


if __name__ == "__main__":
    n, m = 3, 2
    x = cp.Parameter((1, n))
    A = cp.Parameter((n, m))
    A_tch = torch.randn((n, m))
    u = cp.Variable((1, m))
    obj = cp.Minimize(x @ A @ u.T)
    constraints = [cp.norm(u) <= 1]
    prob = cp.Problem(obj, constraints)
    x.value = np.random.randn(1, n)
    cvxpylayer = CvxpyLayer(prob, parameters=[A], variables=[u])
    sol, = cvxpylayer(A_tch)  # DPP error
```

Even only injecting `A` into `CvxpyLayer`, the MWE gave me an error as it's not DPP.
```python3
Traceback (most recent call last):
  File "/Users/jinrae/github/other-projects/parametrised-convex-q-learning/tmp/tmp.py", line 17, in <module>
    cvxpylayer = CvxpyLayer(prob, parameters=[A], variables=[u])
  File "/Users/jinrae/Library/Caches/pypoetry/virtualenvs/parametrised-convex-q-learning-2h6IOcxJ-py3.9/lib/python3.9/site-packages/cvxpylayers/torch/cvxpylayer.py", line 79, in __init__
    raise ValueError('Problem must be DPP.')
ValueError: Problem must be DPP.
```

Can the CvxpyLayer hide unused cvxpy Parameters as constants for this usage?

**Comment by SteveDiamond** [comment]
Thanks for the feature request. Unfortunately this isn't something we can support in cvxpylayers due to how DPP canonicalization works.

The problem `x @ A @ u.T` contains a product of two parameters (`x` and `A`), which violates CVXPY's DPP rules — the problem must be affine in its parameters. This is a CVXPY-level constraint, not a cvxpylayers one.

If we were to substitute `x.value` as a constant to make the problem DPP-compliant, the canonicalized cone program matrices would depend on `x.value`. That means every time `x` changes, we'd need to re-canonicalize the problem — which defeats the purpose of cvxpylayers (canonicalize once, solve many times).

The workaround is to reconstruct the `CvxpyLayer` when `x` changes, or reformulate the problem so that it's DPP with all parameters included.
