### ISSUE TITLE
Minimal LQR example problem: "Can't apply Jacobian with a quadratic objective"

### ISSUE THREAD

**Issue by sai-prasanna** [cvxgrp/cvxpylayers#137]
Hi, I ran into this a bug while using cvxplylayers in my research. 

So I tried a minimal LQR example from COCP paper instead and ran into the same issue.

Source: https://github.com/cvxgrp/cocp/blob/master/lqr.ipynb
I have just put a very minimal example from the file above.
```python
import numpy as np
import cvxpy as cp
from cvxpylayers.torch import CvxpyLayer
import torch
np.random.seed(0)

# generate problem data
n, m = 4, 2
noise = np.sqrt(0.25)
Q0 = np.eye(n)
R0 = np.eye(m)
A = np.random.randn(n, n)
A /= np.max(np.abs(np.linalg.eig(A)[0]))
B = np.random.randn(n, m)
W = noise**2 * np.eye(n)
# set up policy
x = cp.Parameter((n, 1))
P_sqrt = cp.Parameter((n, n))

u = cp.Variable((m, 1))
xnext = cp.Variable((n, 1))

objective = cp.quad_form(u, R0) + cp.sum_squares(P_sqrt @ xnext)
constraints = [xnext == A @ x + B @ u]
prob = cp.Problem(cp.Minimize(objective), constraints)
policy = CvxpyLayer(prob, [x, P_sqrt], [u])
# initialize parameters
Qt, Rt, At, Bt = map(torch.from_numpy, [Q0, R0, A, B])
P_sqrt = torch.eye(n).double(); P_sqrt.requires_grad_(True);

x_batch = torch.randn(1, n, 1).double()
out = policy(x_batch, P_sqrt)[0]
torch.norm(out).sum().backward() # Just to test whether gradients can be computed
```

It raises the following error in cvx library,
```
Traceback (most recent call last):
  File "/home/sai/Desktop/diff_mpc/c_lqr.py", line 157, in <module>
    l.backward()
  File "/home/sai/miniconda3/envs/mbmpc/lib/python3.9/site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/home/sai/miniconda3/envs/mbmpc/lib/python3.9/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/sai/miniconda3/envs/mbmpc/lib/python3.9/site-packages/torch/autograd/function.py", line 267, in apply
    return user_fn(self, *args)
  File "/home/sai/miniconda3/envs/mbmpc/lib/python3.9/site-packages/cvxpylayers/torch/cvxpylayer.py", line 344, in backward
    del_param_dict = compiler.apply_param_jac(
  File "/home/sai/miniconda3/envs/mbmpc/lib/python3.9/site-packages/cvxpy/reductions/dcp2cone/cone_matrix_stuffing.py", line 208, in apply_param_jac
    raise ValueError("Can't apply Jacobian with a quadratic objective.")
ValueError: Can't apply Jacobian with a quadratic objective.
Segmentation fault (core dumped)
```

I am pretty new to solving control problems, let alone differentiable convex optimization, so couldn't really debug this one. Let me know if I can provide more details or if I am doing something wrong.

**Comment by sai-prasanna** [comment]
Fixed it by installing previous version of cvxpy `pip install cvxpy==1.2.0`

**Comment by sai-prasanna** [comment]
It might be better if you pin the compatible cvxpy, currently the constraint in setup.py is just greater than some lower bound version.
