### ISSUE TITLE
AttributeError: 'ConeDims' object has no attribute 'nonpos'

### ISSUE THREAD

**Issue by cryu854** [cvxgrp/cvxpylayers#58]
Hi,
I encountered an AttributeError while testing the below sample code in tensorflow 2.2.0.

```
import cvxpy as cp
import tensorflow as tf
from cvxpylayers.tensorflow import CvxpyLayer

n, m = 2, 3
x = cp.Variable(n)
A = cp.Parameter((m, n))
b = cp.Parameter(m)
constraints = [x >= 0]
objective = cp.Minimize(0.5 * cp.pnorm(A @ x - b, p=1))
problem = cp.Problem(objective, constraints)
assert problem.is_dpp()

cvxpylayer = CvxpyLayer(problem, parameters=[A, b], variables=[x])
A_tf = tf.Variable(tf.random.normal((m, n)))
b_tf = tf.Variable(tf.random.normal((m,)))

with tf.GradientTape() as tape:
  # solve the problem, setting the values of A, b to A_tf, b_tf
  solution, = cvxpylayer(A_tf, b_tf)
  summed_solution = tf.math.reduce_sum(solution)
# compute the gradient of the summed solution with respect to A, b
gradA, gradb = tape.gradient(summed_solution, [A_tf, b_tf])
```

More detailed for the AttributeError：
```
Traceback (most recent call last):
  File ".\model.py", line 15, in <module>
    cvxpylayer = CvxpyLayer(problem, parameters=[A, b], variables=[x])
  File "C:\Users\cryu854\Anaconda3\lib\site-packages\cvxpylayers\tensorflow\cvxpylayer.py", line 102, in __init__
    self.cones = utils.dims_to_solver_dict(data['dims'])
  File "C:\Users\cryu854\Anaconda3\lib\site-packages\cvxpylayers\utils.py", line 4, in dims_to_solver_dict
    "l": int(cone_dims.nonpos),
AttributeError: 'ConeDims' object has no attribute 'nonpos'
```

So I checked the version of my packages, I think the versions meet the requirements.
```
python = 3.7.4
tensorflow = 2.2.0
cvxpy = 1.1.0
diffcp = 1.0.13
Numpy = 1.15
```

After that, I traced the error and temporarily changed `nonpos` to `nonneg` , then the error disappeared and the result seems to work fine for now, but I know this would be failed somewhere.
```
def dims_to_solver_dict(cone_dims):
      cones = {
          "f": int(cone_dims.zero),
          "l": int(cone_dims.nonneg),
          "q": [int(v) for v in cone_dims.soc],
          "ep": int(cone_dims.exp),
          "s": [int(v) for v in cone_dims.psd]
      }
      return cones
```

Hope someone has a solution to this.

**Comment by akshayka** [comment]
Thanks for reporting! We’ll fix this soon.

**Comment by akshayka** [comment]
@cryu854, a new version of CVXPY Layers with the fix should be on PyPi later today. We'll notify you here once it's been uploaded.

**Comment by akshayka** [comment]
The fix is now on PyPI. You can download it with

```
pip install --upgrade cvxpylayers
```

Thanks again for reporting this issue! Please let us know if you run into any other problems.

**Comment by cryu854** [comment]
Thank you for your hard work !
